apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ysoy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-ysoy@sha256:001ae336b1393afcf0b8b348d028dba5a6563985aaecd57e3bce8f4835e8fcf0
        name: my-nodejs
        resources: {}
status: {}
